#!/bin/sh

rm -f /var/luci-indexcache*
rm -f /tmp/luci-indexcache*

[ -x /etc/init.d/rpcd ] && /etc/init.d/rpcd reload

logger -t netshift "luci-app-netshift uci-defaults: cleared LuCI menu cache"

exit 0